export enum AuditEventType {
    // Authentication Events
    USER_LOGIN_INITIATED = 'USER_LOGIN_INITIATED',
    USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE',
    USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS',
    OAUTH_LOGIN_INITIATED = 'OAUTH_LOGIN_INITIATED',
    OAUTH_CALLBACK_RECEIVED = 'OAUTH_CALLBACK_RECEIVED',
    OAUTH_PROFILE_PROCESSED_SUCCESS = 'OAUTH_PROFILE_PROCESSED_SUCCESS',
    OAUTH_PROFILE_PROCESSED_FAILURE = 'OAUTH_PROFILE_PROCESSED_FAILURE',
    TOKEN_ISSUED_SUCCESS = 'TOKEN_ISSUED_SUCCESS',
    TOKEN_REFRESH_INITIATED = 'TOKEN_REFRESH_INITIATED',
    TOKEN_REFRESH_SUCCESS = 'TOKEN_REFRESH_SUCCESS',
    TOKEN_REFRESH_FAILURE = 'TOKEN_REFRESH_FAILURE',
    TOKEN_VALIDATION_SUCCESS = 'TOKEN_VALIDATION_SUCCESS',
    TOKEN_VALIDATION_FAILURE = 'TOKEN_VALIDATION_FAILURE', // More generic than API_KEY_AUTHENTICATION_FAILURE
    API_KEY_AUTHENTICATION_FAILURE = 'API_KEY_AUTHENTICATION_FAILURE', // Specific for API keys if used

    // Authorization Events
    AUTHORIZATION_CHECK_SUCCESS = 'AUTHORIZATION_CHECK_SUCCESS',
    AUTHORIZATION_CHECK_FAILURE = 'AUTHORIZATION_CHECK_FAILURE',

    // IAP Events
    IAP_VALIDATION_REQUESTED = 'IAP_VALIDATION_REQUESTED',
    IAP_VALIDATION_APPLE_SUCCESS = 'IAP_VALIDATION_APPLE_SUCCESS',
    IAP_VALIDATION_APPLE_FAILURE = 'IAP_VALIDATION_APPLE_FAILURE',
    IAP_VALIDATION_GOOGLE_SUCCESS = 'IAP_VALIDATION_GOOGLE_SUCCESS',
    IAP_VALIDATION_GOOGLE_FAILURE = 'IAP_VALIDATION_GOOGLE_FAILURE',
    IAP_TRANSACTION_RECORDED = 'IAP_TRANSACTION_RECORDED',

    // Cryptography Events
    ENCRYPTION_REQUESTED = 'ENCRYPTION_REQUESTED',
    ENCRYPTION_SUCCESS = 'ENCRYPTION_SUCCESS',
    ENCRYPTION_FAILURE = 'ENCRYPTION_FAILURE',
    DECRYPTION_REQUESTED = 'DECRYPTION_REQUESTED',
    DECRYPTION_SUCCESS = 'DECRYPTION_SUCCESS',
    DECRYPTION_FAILURE = 'DECRYPTION_FAILURE',
    HASHING_EXECUTED = 'HASHING_EXECUTED',

    // Secret Management Events
    SECRET_ACCESS_REQUESTED = 'SECRET_ACCESS_REQUESTED',
    SECRET_ACCESS_SUCCESS = 'SECRET_ACCESS_SUCCESS',
    SECRET_ACCESS_FAILURE = 'SECRET_ACCESS_FAILURE',

    // User Management (if applicable in this service, or for context)
    USER_REGISTRATION_INITIATED = 'USER_REGISTRATION_INITIATED',
    USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS',
    USER_REGISTRATION_FAILURE = 'USER_REGISTRATION_FAILURE',
    USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED',
    PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS',
    PASSWORD_CHANGE_FAILURE = 'PASSWORD_CHANGE_FAILURE',
    PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',

    // System Events
    SERVICE_STARTED = 'SERVICE_STARTED',
    SERVICE_STOPPED = 'SERVICE_STOPPED',
    CONFIGURATION_LOADED = 'CONFIGURATION_LOADED',
    HEALTH_CHECK_PERFORMED = 'HEALTH_CHECK_PERFORMED',
    EXTERNAL_API_CALL_INITIATED = 'EXTERNAL_API_CALL_INITIATED',
    EXTERNAL_API_CALL_SUCCESS = 'EXTERNAL_API_CALL_SUCCESS',
    EXTERNAL_API_CALL_FAILURE = 'EXTERNAL_API_CALL_FAILURE',

    // Generic / Uncategorized
    GENERAL_INFO = 'GENERAL_INFO',
    GENERAL_WARNING = 'GENERAL_WARNING',
    GENERAL_ERROR = 'GENERAL_ERROR',
}